apiVersion: apps/v1
kind: Deployment
metadata:
 name: api
spec:
 strategy:
   rollingUpdate:
     maxSurge: 2
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 2
 selector:
   matchLabels:
     app: api
 template:
   metadata:
     labels:
       app: api
   spec:
     containers:
       - name: api
         image: us-central1-docker.pkg.dev/mlops-3/Atforestry/api:latest
         resources:
           limits:
             cpu: "500m"
             memory: "512Mi"
           requests:
             cpu: "500m"
             memory: "512Mi"
         ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 8000
  selector:
    app: api
  clusterIP: None