apiVersion: apps/v1
kind: Deployment
metadata:
 name: API
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: API
 template:
   metadata:
     labels:
       app: API
   spec:
     containers:
       - name: API
         image: us-central1-docker.pkg.dev/mlops-3/Atforestry/API:latest
         resources:
           limits:
             cpu: "1"
             memory: "4Gi"
           requests:
             cpu: "1"
             memory: "4Gi"
         ports:
           - containerPort: 8000
         env:
           - name: POSTGRES_USER
             value: postgres
           - name: POSTGRES_PASSWORD
             value: postgres
           - name: POSTGRES_DB
             value: atforestry
           - name: PGDATA
             value: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: API
spec:
  ports:
    - port: 8000
  selector:
    app: API
  clusterIP: None