apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-query
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: user-query
 template:
   metadata:
     labels:
       app: user-query
   spec:
     containers:
       - name: user-query
         image: us-central1-docker.pkg.dev/mlops-3/Atforestry/user-query:latest
         resources:
           limits:
             cpu: "1"
             memory: "4Gi"
           requests:
             cpu: "1"
             memory: "4Gi"
         ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: user-query
spec:
  ports:
    - port: 8000
  selector:
    app: user-query
  type: LoadBalancer     